### PR TITLE
 Project: Bare Metal Forms and Helpers

### PR DESCRIPTION
**Pull request by tanzila-abedin**
1. HTML Form
2. Railsy Forms with #form_tag
3. Railsy-er Forms with #form_with

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS:CHANGES REQUIRED** :recycle: :construction: :construction_worker_woman: 

Good effort. :+1: 

**Highlight**
- You followed the project instructions carefully. :clap: 

**Required changes**
Please see my inline comment as well.

- [x] Do not work directly in the “development” branch. Create a “feature-branch” branch (give it a descriptive name) based on the “development” branch for the feature you implement.  Please correct this error.
- [x] A new user cannot be created due to the error I explained in my inline comment below. :point_down: 
- [x] Please remove the unused commented code in your user controller.
- [x] Your routes should look something like this: ` resources :users, only: [:new, :create, :edit, :update]` since you don't have a destroy controller action. 
- [x] Your UsersController create action should redirect_to new_user_path if user was saved and render :new if user was not saved. 
- [x] update action should redirect_to edit_user_path(user_params) if user was saved and render :edit if user was not saved.

[OPTIONAL]

- [x] Form view should display a list of the error messages (with #errors and full_messages usage).

Please make the required changes and submit another CRR when you're ready. 

In need of clarification, please drop your message here and mention me. You can as well hit me up on slack.

Cheers and happy coding :smile:

**Comment by tanzila-abedin** [comment]
I have made the requested changes. Thank you.

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: 
-----------
Hello @tanzila-abedin Great job working on the required changes :clap: 
However, there are a few changes to make to complete this project :+1: :wrench: see them below :eyes: :point_down:
-----------

- [x] Please make sure you work correctly with the Git Flow. You are requesting to merge to master, It must be merge to development. Please fix this. [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) is a reminder of how to work with Git Flow
- [x] You don't have the commented out code please add it. 
- [x] Please check the edit action that is not updating the information. 
- [x] Please fix the broken issue link on your readme file. 
----------------
Make these required changes and send it again for another review :clap: :100: 
HAPPY CODING!!!

**Comment by tanzila-abedin** [comment]
I have made previously requested changes. Thank you.

**Review by george-shammar — APPROVED** [review]
### **STATUS:APPROVED** :heavy_check_mark: :heavy_check_mark: :+1: :clap: 

Great job.

**Hightlight**
- You've implemented all the required changes. :+1: Congratulations! :wine_glass: 

NB: For this project, you are expected to have a master branch, development(default) and feature branch. Pull Request is supposed to be from feature branch to development. 

Cheers and good luck with your future projects. :smile:

**Pull request merged**
